import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Input from "../components/Input";
import Photos from "../components/Photos";
import Title from "../components/Title";
import Main from "../components/Main";
import Footer from "../components/Footer";
import { createApi, toJson } from "unsplash-js";

const unsplash = createApi({
  accessKey: process.env.NEXT_PUBLIC_API_KEY,
});

export default function Home() {
  const router = useRouter();
  const [search, setSearch] = useState(router.query.search || "");
  const [pictures, setPictures] = useState([]);
  const [page, setPage] = useState(1);

  // Search from input
  useEffect(() => {
    const searchPhotos = async () => {
      router.push(`/?search=${search}`, undefined, { shallow: true });

      unsplash.search
        .getPhotos({ query: search, page, perPage: 16 })
        .then(toJson)
        .then((json) => {
          setPictures([]);
          setPictures(json.response.results);
        });
    };

    if (!search) return;

    searchPhotos();
  }, [search]);

  // Get daily photos
  useEffect(() => {
    if (search) return;
    const getDailyPhotos = async () => {
      unsplash.photos
        .getRandom({
          count: 24,
        })
        .then(toJson)
        .then((json) => {
          setPictures((pictures) => [...pictures, ...json.response]);
        });
    };

    getDailyPhotos();
  }, [page]);

  // Load more
  useEffect(() => {
    if (!search) return;
    const searchPhotos = async () => {
      unsplash.search
        .getPhotos({ query: search, page })
        .then(toJson)
        .then((json) => {
          setPictures((pictures) => [...pictures, ...json.response.results]);
        });
    };

    searchPhotos();
  }, [page]);

  const handleLoadMore = () => {
    setPage(page + 1);
  };

  return (
    <div>
      <Head>
        <title>Photo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Input handleSubmit={setSearch} />
        <Title>{search || "Daily"} Pictures</Title>
        <Photos pictures={pictures} handleLoadMore={handleLoadMore} />
      </Main>

      <Footer />
    </div>
  );
}
