import { useState, useEffect } from "react";
import { css } from "@emotion/react";
import styled from "@emotion/styled";
import Head from "next/head";
import Input from "../components/Input";
import Photo from "../components/Photo";
import { createApi, toJson } from "unsplash-js";

const Main = styled.div(
  () => css`
    padding: 1.6rem;
  `
);

export default function Home() {
  const [search, setSearch] = useState("");
  const [pictures, setPictures] = useState([]);

  const unsplash = createApi({
    accessKey: "ggPLSD6QWCQ6G4IttYDd4zVvcw6iVznaVTLiDxocKKM",
  });

  useEffect(() => {
    const searchPhotos = async () => {
      unsplash.search
        .getPhotos({ query: search })
        .then(toJson)
        .then((json) => {
          setPictures(json.response.results);
        });
    };

    searchPhotos();
  }, [search, unsplash.search]);

  return (
    <div>
      <Head>
        <title>Photo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Input handleSubmit={setSearch} />
        <Photo pictures={pictures} />
      </Main>

      <footer></footer>
    </div>
  );
}
